# Generated by Django 4.1.2 on 2024-01-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesoffred',
            name='image',
            field=models.ImageField(blank=True, default='Screenshot_from_2024-01-19_16-57-31.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='Screenshot_from_2024-01-19_16-57-31.png', null=True, upload_to='images/'),
        ),
    ]
