# Generated by Django 4.1.2 on 2024-06-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0003_servicesoffred_image_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='about_avatar',
        ),
        migrations.RemoveField(
            model_name='homedetails',
            name='avatar_img',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, default='Screenshot_from_2024-01-19_16-57-31.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='homedetails',
            name='image',
            field=models.ImageField(blank=True, default='Screenshot_from_2024-01-19_16-57-31.png', null=True, upload_to='images/'),
        ),
    ]
